name: Release

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: [[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}